version: '3'

services:
  sandbox:
    image: golang
    volumes:
      - ./sandbox:/sandbox
    working_dir: /sandbox
    tty: true

  dns:
    image: coredns/coredns
    ports:
      - "53:53/udp"

  memcache:
    image: memcached
    expose:
      - "11211/tcp"
      - "11211/udp"
    ports:
      - "11211:11211/tcp"
      - "11211:11211/udp"
    command: "memcached -U 11211"

  chargen:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
    expose:
      - "19/udp"
    ports:
      - "19:19/udp"
    tty: true
    command: sh -c "service xinetd start; /bin/sh"

  ntp:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
    expose:
      - "123/udp"
    ports:
      - "123:123/udp"
    tty: true
    command: sh -c "service ntp start; /bin/sh"

  miniupnp:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
    expose:
      - "1900/udp"
      - "5351/udp"
    ports:
      - "1900:1900/udp"
      - "5351:5351/udp"
    tty: true
    cap_add:
      - NET_ADMIN
    command: sh -c "service miniupnpd start; /bin/sh"
